In [1]:
import pandas

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.models import Model, Input, load_model
from keras.layers import Embedding, Dense, Dropout
from keras.layers import Conv1D, GlobalMaxPooling1D
from keras.layers import Concatenate

import numpy as np

from sklearn.metrics import precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

Using TensorFlow backend.


In [2]:
# encode class values as integers
def convert_label(Y):
    encoder = LabelEncoder()
    encoder.fit(Y)
    encoded_Y = encoder.transform(Y)
    # convert integers to dummy variables (i.e. one hot encoded)
    dummy_y = np_utils.to_categorical(encoded_Y)
    #print(dummy_y)
    return dummy_y

In [3]:
# load dataset
dataframe = pandas.read_csv("iris.csv", header=None)
dataset = dataframe.values
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]
#print(Y)
Y = convert_label(Y)
#print(Y)
print(len(X))
print(len(Y))

150
150


In [4]:
# split train set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y , random_state =7, test_size=0.20)
print(len(X_train))
print(len(Y_train))
print(len(X_test))
print(len(Y_test))

120
120
30
30


In [5]:
print(Y_train)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1.

In [5]:
# define baseline model
inputs = Input(shape=(4,))
dense1 = Dense(8, activation='relu')(inputs)
dense2 = Dense(12, activation='relu')(dense1)
outputs = Dense(3, activation='softmax')(dense2)
model = Model(inputs, outputs)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())


Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 12)                108       
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 39        
Total params: 187
Trainable params: 187
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
# Fit the model
model.fit(X_train, Y_train, epochs=10, batch_size=10,  verbose=2)

Epoch 1/10
 - 0s - loss: 0.5936 - acc: 0.6611
Epoch 2/10
 - 0s - loss: 0.5692 - acc: 0.6694
Epoch 3/10
 - 0s - loss: 0.5459 - acc: 0.7361
Epoch 4/10
 - 0s - loss: 0.5237 - acc: 0.7667
Epoch 5/10
 - 0s - loss: 0.5034 - acc: 0.7694
Epoch 6/10
 - 0s - loss: 0.4822 - acc: 0.7778
Epoch 7/10
 - 0s - loss: 0.4601 - acc: 0.7806
Epoch 8/10
 - 0s - loss: 0.4396 - acc: 0.7833
Epoch 9/10
 - 0s - loss: 0.4201 - acc: 0.7806
Epoch 10/10
 - 0s - loss: 0.4006 - acc: 0.7833


In [9]:
# calculate predictions
y_preds = model.predict(X_test,verbose=1)

# compute the accuracy
yhat = []
for pred in y_preds:
    yhat.append(np.argmax(pred))

yhat = to_categorical(yhat)
#print(yhat)

print(classification_report(Y_test, yhat))

30/30 [==============================] - 0s 17us/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.78      0.58      0.67        12
           2       0.64      0.82      0.72        11

   micro avg       0.77      0.77      0.77        30
   macro avg       0.81      0.80      0.80        30
weighted avg       0.78      0.77      0.76        30
 samples avg       0.77      0.77      0.77        30

